version: '3'

services:
  api:
    image: "11904212.azurecr.io/pcc-demo-api:latest"
    container_name: "pcc-demo-api"
    restart: unless-stopped
    ports:
      - 8080:8080
  ui:
    image: "11904212.azurecr.io/pcc-demo-ui:latest"
    container_name: "pcc-demo-ui"
    restart: unless-stopped
    ports:
      - 4200:80

